services:
  - type: web
    name: vero-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VILLAGE_NAME
        value: KHIJADIYA ગ્રામપંચાયત
      - key: SQLITE_DB_PATH
        value: ""
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_TEMPLATE_NAME
        value: bill_pdf_notification
      - key: WHATSAPP_LANGUAGE_CODE
        value: gu

  - type: web
    name: vero-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
